[package]
name = "atomic-bomb-engine-py"
version = "0.42.0"
edition = "2024"

[lib]
name = "atomic_bomb_engine"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-bomb-engine = "0.41.1"
#atomic-bomb-engine = { git = "https://github.com/we-lsp/atomic-bomb-engine.git", branch = "ExponentialMovingAverage"}
tokio = "1"
pyo3-async-runtimes = { version = "0.27", features = ["attributes", "tokio-runtime"] }
serde_json = { version = "1.0", features = [] }
futures = "0.3"
anyhow = "1.0"
serde = "1.0.202"

[build]
rustflags = ["-C", "target-feature=+crt-static"]


[dependencies.pyo3]
version = "0.27"
features = ["extension-module", "auto-initialize", "serde"]

[tool.maturin]
name = "atomic_bomb_engine"
scripts = "python/atomic_bomb_engine"
