name: Build and publish Python wheels for Alpine Linux

on:
  push:
    branches:
      - release

jobs:
  build-wheels:
    name: Build wheels on Alpine Linux
    runs-on: alpine-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: 签出rust代码
        uses: actions/checkout@v2

      - name: 签出前端
        uses: actions/checkout@v2
        with:
          repository: GiantAxeWhy/atomic-bomb-engine-front
          path: vue-project

      - name: 安装Node.js
        run: apk add --no-cache nodejs npm

      - name: 构建前端
        run: |
          cd vue-project  
          npm install
          npm run build

      - name: 删除原有dist
        run: rm -rf python/atomic_bomb_engine/dist/*

      - name: 复制dist到Python项目
        run: cp -r vue-project/dist/* python/atomic_bomb_engine/dist/

      - name: 安装Python和Rust
        run: apk add --no-cache python3 python3-dev rust

      - name: 安装maturin
        run: pip install maturin

      - name: 构建wheels
        run: maturin build --release --interpreter python${{ matrix.python-version }}

      - name: 安装Twine
        run: pip install twine

      - name: 上传wheels到PyPI
        env:
          TWINE_USERNAME: your_username
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ target/wheels/*.whl
