name: Build and publish Python wheels for CentOS 8

on:
  push:
    branches:
      - release
      - release-rc.*

jobs:
  build-wheels:
    name: Build wheels on CentOS 8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: 签出代码
        uses: actions/checkout@v2

      - name: 签出前端
        uses: actions/checkout@v2
        with:
          repository: GiantAxeWhy/atomic-bomb-engine-front
          path: vue-project

      - name: 启动 Node.js 容器
        run: |
          docker run --name node-container -d -v "${{ github.workspace }}:/workspace" -w "/workspace/vue-project" node:18 sleep 3600

      - name: 构建前端
        run: |
          docker exec node-container npm install
          docker exec node-container npm run build

      - name: 复制构建结果到 Runner
        run: |
          docker cp node-container:/workspace/vue-project/dist ./vue-project/dist

      - name: 停止并删除 Node.js 容器
        run: |
          docker stop node-container
          docker rm node-container

      - name: 启动 AlmaLinux 容器
        run: |
          docker run --name python-almalinux-container -d -v "${{ github.workspace }}:/workspace" -w "/workspace" almalinux:8 sleep 3600

      - name: 安装构建工具
        run: |
          docker exec python-almalinux-container yum install -y epel-release
          docker exec python-almalinux-container yum install -y gcc gcc-c++ make

      - name: 安装 pyenv 和指定版本的 Python
        run: |
          docker exec python-almalinux-container yum install -y git curl openssl-devel bzip2-devel zlib-devel readline-devel sqlite-devel
          docker exec python-almalinux-container sh -c "curl https://pyenv.run | bash"
          docker exec python-almalinux-container sh -c 'export PATH="/root/.pyenv/bin:$PATH" && eval "$(pyenv init --path)" && for version in ${{ join(matrix.python-version, ' ') }}; do pyenv install $version; pyenv global $version; curl https://bootstrap.pypa.io/get-pip.py | python; done'

      - name: 安装 Rust、maturin 和 patchelf
        run: |
          docker exec python-almalinux-container yum install -y rust cargo patchelf
          docker exec python-almalinux-container sh -c 'export PATH="/root/.pyenv/shims:$PATH" && pip install maturin'

      - name: 使用 maturin 构建 wheels
        run: |
          docker exec python-almalinux-container sh -c '
            export PATH="/root/.pyenv/bin:$PATH" && eval "$(pyenv init --path)"
            for version in ${{ join(matrix.python-version, ' ') }}; do
              pyenv global $version
              maturin build --release
            done'

      - name: 复制 wheels 到 Runner
        run: docker cp python-almalinux-container:/workspace/target/wheels ./

      - name: 安装 Twine
        run: pip install twine

      - name: 上传 wheels 到 PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheels/*.whl
