name: Build and publish Python wheels for musl/Linux

on:
  push:
    branches:
      - release

jobs:
  build-wheels:
    name: Build wheels on Alpine
    runs-on: ubuntu-latest

    steps:
      - name: 签出rust代码
        uses: actions/checkout@v2

      - name: 签出前端
        uses: actions/checkout@v2
        with:
          repository: GiantAxeWhy/atomic-bomb-engine-front
          path: vue-project

      - name: 启动 Python Alpine 容器
        run: |
          docker run --name python-alpine-container -d -v "${{ github.workspace }}:/__w" -w "/__w" python:3.12-alpine sleep 3600

      - name: 安装Node.js和构建工具
        run: |
          docker exec python-alpine-container apk add --no-cache nodejs npm build-base

      - name: 构建前端
        run: |
          docker exec python-alpine-container sh -c "cd vue-project && npm install && npm run build"

      - name: 删除现有的dist目录
        run: docker exec python-alpine-container rm -rf python/atomic_bomb_engine/dist/*

      - name: 将dist复制到Python项目
        run: docker exec python-alpine-container cp -r vue-project/dist/* python/atomic_bomb_engine/dist/

      - name: 安装 Rust、maturin 和 patchelf
        run: |
          docker exec python-alpine-container apk add --no-cache openssl-dev pkgconfig rust cargo patchelf
          docker exec python-alpine-container pip install maturin

      - name: 安装依赖和工具
        run: |
          docker exec python-alpine-container apk add --no-cache openssl-dev pkgconfig rust cargo
          docker exec python-alpine-container pip install maturin

      - name: 使用 maturin 构建代码
        env:
          OPENSSL_DIR: /usr/lib
        run: |
          docker exec python-alpine-container sh -c "maturin build --release"

      - name: 安装 Twine 并上传
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          docker exec python-alpine-container pip install twine
          docker exec python-alpine-container twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ target/wheels/*.whl
