name: Build and publish Python wheels for Linux

on:
  push:
    branches:
      - release

jobs:
  build-wheels:
    name: Build wheels on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - name: 安装 musl-tools 和 OpenSSL (musl 版本)
        run: |
          sudo apt update
          sudo apt install -y musl-tools
          sudo apt install -y musl-dev
          sudo apt install -y libssl-dev

      - name: 查找 OpenSSL 头文件和库文件
        run: |
          echo "查找 opensslconf.h 文件..."
          find /usr -name opensslconf.h
          echo "查找 libssl 库文件..."
          find /usr -name libssl.so

      - name: 配置环境变量 (通用)
        run: |
          echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/openssl" >> $GITHUB_ENV

      - name: 特定配置环境变量 (musl)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          echo "OPENSSL_LIB_DIR=/path/to/musl/openssl/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/path/to/musl/openssl/include" >> $GITHUB_ENV

      - name: 签出rust代码
        uses: actions/checkout@v2

      - name: 签出前端
        uses: actions/checkout@v2
        with:
          repository: GiantAxeWhy/atomic-bomb-engine-front
          path: vue-project

      - name: 安装Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 构建前端
        run: |
          cd vue-project
          npm install
          npm run build

      - name: 删除原有dist
        run: rm -rf python/atomic_bomb_engine/dist/*

      - name: 复制dist到Python项目
        run: cp -r vue-project/dist/* python/atomic_bomb_engine/dist/

      - name: 设置python环境
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 添加musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: 安装maturin
        run: pip install maturin

      - name: 构建glibc wheels
        run: maturin build --release --interpreter python${{ matrix.python-version }}

      - name: 构建musl wheels
        run: maturin build --release --target x86_64-unknown-linux-musl --interpreter python${{ matrix.python-version }}

      - name: 安装Twine
        run: pip install twine

      - name: 上传wheels到PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ target/wheels/*.whl
